# Generated by Django 4.1 on 2022-09-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_rename_commentname_comment_post_comment_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='replyName',
            new_name='comment',
        ),
        migrations.AddField(
            model_name='reply',
            name='name',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
