# Generated by Django 4.1 on 2022-09-08 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_rename_replyname_reply_comment_reply_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='commentName',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='comment',
            new_name='replyName',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='name',
        ),
    ]
