# Generated by Django 4.1 on 2022-09-09 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_alter_reply_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={},
        ),
    ]
